name: Format Check

# Run on all push and pull requests
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # 11:30 PM UTC every Sunday
    - cron:  '30 23 * * 0'

jobs:
  format-check:
    name: Run format check
    uses: nasa/cFS/.github/workflows/format-check.yml@main