name: Static Analysis

# Run on main push and pull requests
on:
  push:
  pull_request:

jobs:

  static-analysis:
    name: Run cppcheck
    uses: nasa/cFS/.github/workflows/static-analysis.yml@main
